### ISSUE TITLE
Room.js Verifier si place et si joueur != existe dans la room

### ISSUE THREAD

**Issue by H04K** [GabeNThePrimaryGod/Sandbox.io#12]
if(clientData.socket)
        {
            // TODO : verifier si il y a de la place dans la room (avec Room.players)
            // TODO : verifier si le joueur n'existe pas deja

            this.players[clientData.socket.id] = new Player(clientData);

            console.log(`[${this.UID}:${this.name}] [+] Le joueur [${this.players[clientData.socket.id].name}] a rejoin la room`);
            this.emit('playerConnect', this.players[clientData.socket.id], this); 

            clientData.socket.emit('joinResponse', 
            {
                success: true, 
                roomName: this.name, 
                roomUID: this.UID, 
                playerName: this.players[clientData.socket.id].name
            });

**Comment by GabeNThePrimaryGod** [comment]
ça aussi ça devrais pas exister
