### ISSUE TITLE
JoininManager.js Lorsque le joueur n'a pas de nom recup le nom donné par le serveur

### ISSUE THREAD

**Issue by H04K** [GabeNThePrimaryGod/Sandbox.io#16]
this.globalSocket.on('getRoomsResponse', (rooms) => {
            // cette verification n'est que coter client elle ne sert qu'a éviter les bugs client 
            // elle n'est pas une preuve que la room existe ou pas il ne faut donc pas si fier coter serveur 
            if (rooms[UID]) {
                // TODO : lorsque le joueur na pas de nom recuperer le nom que le serveur lui donne

**Comment by GabeNThePrimaryGod** [comment]
wtf pourquoi ça existe encore ça
